apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: {{ .Values.namespaceName }}
spec:
  ports:
    - protocol: {{ .Values.serviceProtocol }}
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.serviceTargetPort }}
  type: {{ .Values.serviceType }}